## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python

### What is an array

An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

In [20]:
# import numpy
import numpy as np

In [21]:
list = [1,2,3,4,5,6]

In [22]:
arr = np.array(list)

In [23]:
arr

array([1, 2, 3, 4, 5, 6])

In [24]:
print(type(arr))

<class 'numpy.ndarray'>


In [25]:
# let's try to provide heterogenous data to array

In [26]:
list2 = [1,2,3,4,5,10.5,'vishal']

In [27]:
arr1 = np.array(list2)

In [28]:
arr1

array(['1', '2', '3', '4', '5', '10.5', 'vishal'], dtype='<U32')

In [29]:
type(arr1)

numpy.ndarray

In [30]:
#it is one dimensional array

In [31]:
arr.shape # it provide number of rows and columns

(6,)

In [32]:
# if w ewant to know the dimensio of the array

In [33]:
arr.ndim

1

In [34]:
# if we have one dimesnional arrya then it will provide how many elements we have

In [35]:
# we can convert this one-dimensional array into two dimensional array

In [36]:
# new = np.reshape(a, (-1, ncols))

In [39]:
new = np.reshape(arr,(-1,2))

In [42]:
new

array([[1, 2],
       [3, 4],
       [5, 6]])

In [43]:
new.shape

(3, 2)

In [45]:
new.ndim

2

In [40]:
new = arr.reshape([2,2])

ValueError: cannot reshape array of size 6 into shape (2,2)

In [46]:
# creating multidimensional array

In [51]:
l1= [1,2,3,4,5,6]
l2 = [7,8,9,10,11,12]
l3 = [13,14,15,16,17,18]

In [52]:
a = np.array([l1,l2,l3])

In [53]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [54]:
a.shape

(3, 6)

In [60]:
a.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [62]:
a.reshape(6,3).shape

(6, 3)

In [57]:
# in one-D array we have only one opening and closing bracket
# in 2-d array w ehave two opening and closing bracket

In [58]:
a.shape

(3, 6)

In [63]:
# while reshaping the array size of elemnt should be same 
# otherwise it will not provide output

### Indexing

In [65]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

### 

### 

In [66]:
a[2]

array([13, 14, 15, 16, 17, 18])

In [67]:
a[4]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [68]:
a[1]

array([ 7,  8,  9, 10, 11, 12])

In [69]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [70]:
a[::]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [72]:
a[0:2,:]

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [77]:
arr[:3:]

array([1, 2, 3])

In [78]:
a[0:2,0:2]

array([[1, 2],
       [7, 8]])

In [79]:
a[1:,3:]

array([[10, 11, 12],
       [16, 17, 18]])

In [84]:
arr = np.arange(0,10) # it will print the values betwwen 0 to 10

In [81]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
# arrange will create one-D array